directories:
  output: dist_electron
  buildResources: assets
appId: com.official-electron-vue.app
productName: Electron Vue
copyright: Copyright © 2025 ${author}
nsis:
  oneClick: true
  allowToChangeInstallationDirectory: false
  deleteAppDataOnUninstall: true
files:
  - filter:
      - dist/**/*
extraResources:
  - filter:
      - defaults/**/*
electronVersion: 36.2.1
